### ISSUE TITLE
Beatitude too big?

### ISSUE THREAD

**Issue by hpfmn** [maltman23/ArduTouch#3]
It seems using a recent Arduino (1.8.5) and avr base library (1.6.20) it is not possible to compile and use the Beatitude example.

Arduino complains that it is too big:

```
Sketch uses 33780 bytes (104%) of program storage space. Maximum is 32256 bytes.
Global variables use 735 bytes (35%) of dynamic memory, leaving 1313 bytes for local variables. Maximum is 2048 bytes.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board Arduino/Genuino Uno.
```

Or is there anything else I'm missing?

**Comment by maltman23** [comment]
Sorry for the long delay in answering this!  
This issue is now addressed in the latest release (28-March-2018).

Beatitude was developed using Arduino software V1.6.6, but when compiled with the latest version of the Arduino software (V1.8.5), the resulting code is too big.  We fixed it by making the drums a little bit lower resolution.  They sound fine!  :)  

But, to get full resolution sound of the drums, you can use V1.6.6 of the Arduino software (instead of the latest version), and uncomment the BUILD_166 define statement in "model.h" in the ArduTouch Arduino library.
