### ISSUE TITLE
Call setAttack() on OneVoxSynth setup()

### ISSUE THREAD

**Issue by michcan** [maltman23/ArduTouch#4]
Hello Mitch and thank you for this nice librairie !
I try to create my own synth sketch. I use the OneSynthVox class. I want to set attack on the creation of the objet. So i called the setAttack() method inside the setup() method, it doesn't work. But it work's inside evHandler() method. What is the best way to get it work ?

#include "ArduTouch.h"                       

set_baud_rate( 115200 )  

class mysynth : public OneVoxSynth
{
   public:
   void setup()
   {
      OneVoxSynth::setup();
      setAttack(100); // it doesn't work
   }

   boolean evHandler( obEvent e )            // event handler
   {
      switch ( e.type() )
      {
         case KEY_DOWN:                      // a key has been pressed
         {    
            setAttack(100); // it work
            return true;                     // KEY_DOWN event was handled
         }
         default:       
            return false;                    // ignore all other events
      }
} synth ;

void setup()
{
   ardutouch_setup( &synth );                   
}

void loop()
{
   ardutouch_loop();                            
}

**Comment by maltman23** [comment]
Sorry for taking so long to answer your question!

Its a good question.  The answer is to be found in the example sketch  _22_Amp_Modifiers.ino, but it should probably be made more explicit:

The reason setAttack() -- or any other setting of control parameters -- will not work when put in the setup() method of the synth is because they will all be wiped out any time the synth is reset. An implicit reset of the synth is conducted by the library at the end of the startup sequence, after setup() has been called -- hence those settings will be lost.

The proper place to put this kind of code is in the "reset handler" of the synth -- the logic which handles '!'  in the charEv(char code) method of the synth.

One way to explain the difference between the code in the 'reset' portion of the synth's charEv() method, and the code in the setup() method is that the former is what gets executed in a soft reset (resetting after the power is already on), and the latter in a hard reset (when you first apply power).

The relevant lines from _22_Amp_Modifiers.ino start at line 238, and are reproduced here:

-------------------  from _22_Amp_Modifiers.ino   (line 238) --------------------

```
   // We initialize our controls in the reset handler for our synth. 
   //
   // The reset handler is the code which is executed when our synth receives
   // a '!' character event. 
   //
   // Note: ardutouch_setup() resets the synth before returning.
 
   boolean charEv( char code )
   {
      switch ( code )
      {
         case '!':                     // reset
         {
            // perform generic reset of the superclass
            
            super::charEv('!');

            //       the following macro will (line-by-line):

            // start keyboard in octave 5,
            // push voice 0 
            // set envelope (decay=68, sustain=64, release=100)
            // push amdMods
            // initialize tremolo control (freq=2.5hz, depth=1.0, unmute)
            // pop ampMods and pop voice 0

            console.exe( PSTR( "k5\\`"
                               "0"
                               "ed68\\s64\\r100\\`"
                               "A"
                               "tf2.5\\d1\\<`"
                               "``" ) );

            break;
         }
         default:
            return super::charEv( code );
      }
      return true;
   }
```
