### ISSUE TITLE
'void ThickSynth::setup()' cannot be overloaded - Arduino 1.8.6 or newer

### ISSUE THREAD

**Issue by domenpk** [maltman23/ArduTouch#5]
I get `'void ThickSynth::setup()' cannot be overloaded` on Arduino 1.8.6 or 1.8.7. I have tried Linux and Windows versions, same error. I also get the same error for different ArduTouch projects.

It works fine on 1.8.5, so I guess that's the immediate mitigation.

I believe it might be related to: https://github.com/arduino/arduino-builder/issues/292

**Comment by ferrisimo** [comment]
I hit this today too. Also found that the 1.9.0 beta works fine.

**Comment by maltman23** [comment]
This is a known issue with v1.8.7 (the newest as of this date) of the Arduino software.  If you use v1.8.5 or before of the Arduino software, all is good.  This problem should be fixed in the next version of the Arduino software.

You can find previous versions of the Arduino software here:
https://www.arduino.cc/en/Main/OldSoftwareReleases#previous

**Comment by maltman23** [comment]
This is now fixed with the latest release!  (We found a work-around for the bug in the Arduino software.)
